<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Role;
use App\Models\User;
use App\Models\Employee;
use App\Models\Customer;
use App\Models\Category;
use App\Models\Supplier;
use App\Models\Product;
use App\Models\City;
use App\Models\Address;
use App\Models\TransactionStatus;
use App\Models\ExpeditionTruck;
use App\Models\BankPayment;
use App\Models\ProductHistory;
use App\Models\Transaction;
use App\Models\DetailTransaction;
use App\Models\TransactionShipping;

use DateTime;
use DateInterval;
use DatePeriod;

use Illuminate\Support\Collection;

use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
        $role = Role::create([
            'name' => 'Super Admin',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        $user = User::create([
            'reference' => 'employee',
            'email' => 'superAdmin@mail.com',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => bcrypt('12345678'),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'deleted_at' => null,
        ])->getAttributes();

        $employee = Employee::create([
            'name' => 'Super Admin',
            'gander' => 'man',
            'phone' => '021111111111',
            'address' => 'Super Admin',
            'date_join' => Carbon::now()->format('Y-m-d'),
            'picture' => 'no-image.jpg',
            'role_id' => $role['id'],
            'user_id' => $user['id'],
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'deleted_at' => null,
        ])->getAttributes();

        $user2 = User::create([
            'reference' => 'customer',
            'email' => 'superCustomer@mail.com',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => bcrypt('12345678'),
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'deleted_at' => null,
        ])->getAttributes();

        $customer = Customer::create([
            'name' => 'Super Customer',
            'phone' => '021111111111',
            'picture' => 'no-image.jpg',
            'user_id' => $user2['id'],
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'deleted_at' => null,
        ])->getAttributes();

        Role::create([
            'name' => 'Owner',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        Role::create([
            'name' => 'Manager',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        Role::create([
            'name' => 'Admin Penjualan',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        Role::create([
            'name' => 'Admin Gudang',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        Role::create([
            'name' => 'Admin Ekspedisi',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        $imageProfil =  [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '1.jpg',
            '5.jpg',
        ];

        for ($i = 1; $i <= 5; $i++) {
            $user = User::create([
                'reference' => 'employee',
                'email' => 'employee' . $i . '@mail.com',
                'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'password' => bcrypt('12345678'),
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ])->getAttributes();

            Employee::create([
                'name' => 'Employee ' . $i,
                'gander' => 'man',
                'phone' => '021111111111',
                'address' => 'Employee ' . $i . ' Address',
                'date_join' => Carbon::now()->format('Y-m-d'),
                'picture' => 'storage/employee/' . $imageProfil[$i - 1],
                'role_id' => $i + 1,
                'user_id' => $user['id'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ])->getAttributes();
        }

        TransactionStatus::create([
            'name' => 'Menunggu Konfirmasi',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        TransactionStatus::create([
            'name' => 'Sedang Dikemas',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        TransactionStatus::create([
            'name' => 'Dalam Antrian Pengiriman',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        TransactionStatus::create([
            'name' => 'Dalam Pengiriman',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        TransactionStatus::create([
            'name' => 'Pengiriman Selesai',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        TransactionStatus::create([
            'name' => 'Pengiriman Selesai - Konfirmasi Pengguna',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        TransactionStatus::create([
            'name' => 'Transaksi Dibatalkan',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->getAttributes();

        $supplier =  [
            'PT. Universal Jaya Perkasa',
            'PT. Limas Timur Pratama',
            'PT. Berdikari Tunggal Perkasa',
            'PT. Karya Baru Indonesia',
            'CV. Kencana Unggul Sentosa',
            'PT. Usaha Pangan Sejahtera',
            'Cahaya Tiga Tunggal',
            'UD. Sido Mumbul',
            'UD. Selatan Jaya',
        ];

        for ($i = 1; $i <= 9; $i++) {
            Supplier::create([
                'name' => $supplier[$i-1],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ])->getAttributes();
        }

        $category =  [
            'Alat Tulis',
            'Beras',
            'Curah',
            'Keperluan Dapur',
            'Kantong Kresek',
            'Sabun',
            'Kopi, Susu, & Teh',
            'Jajanan',
            'Mie Instan',
            'Minuman',
            'Sandal Jepit',
            'Obat-Obatan',
            'Keperluan Bayi',
            'Lainnya',
        ];

        for ($i = 1; $i <= 14; $i++) {
            Category::create([
                'name' => $category[$i-1],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ])->getAttributes();
        }

        $volume =  [
            5100,
            20100,
            10100,
            50100,
            64000,
            14720,
            16800,
            96000,
            4500,
            6000,
        ];

        $unit =  [
            'Karung',
            'Karung',
            'Karung',
            'Karung',
            'Dus',
            'Dus',
            'Dus',
            'Dus',
            'Dus',
            'Dus',
        ];

        $imageProduct =  [
            '1.jpg',
            '2.jpg',
            '3.jpg',
            '1.jpg',
            '5.jpg',
            '6.jpg',
            '7.jpg',
            '8.jpg',
            '9.jpg',
            '10.png',
            '11.png',
            '12.jpg',
            '13.jpg',
            '14.jpg',
            '15.jpg',
            '16.jpg',
            '17.jpg',
            '18.jpg',
            '19.jpg',
            '20.jpg',
        ];

        $product =  [
            'Amplop 110x230',
            'Amplop 95x152',
            'Amplop lam aran',
            'Buku Gambar A4 Ria',
            'Buku Gambar kecil Ria',
            'Buku Tulis Big Boss 42 Lem bar',
            'BUKU TULI S DODO 38 Lem bar',
            'Buku tulis Dodo 58 Lembar',
            'BUKU TULI S LANI 30 Lembar',
            'BUKU TULI S LANI 38 Lembar',
            'BUKU TULI S SEGI TI GA 58 Lem bar',
            'BUKU TULI S SI DU 38 Lem bar',
            'BUKU TULI S SI DU 58 Lem bar',
            'FABER CASTEL 2B',
            'Joyko eraser EB 30',
            'JOYKO PENCIL 2B',
            'KERTAS FOLI O',
            'KERTAS KADO',
            'Lem kertas',
            'PENGGARIS POLOS',
            'Serutan kotak',
            'StandarBolpen',
            'UNI STAR 2B',
            'Bawang putih',
            'Jagung bihun',
            'KACANG TANAH',
            'KACANG HIJAU',
            'Kerupuk nasi uduk',
            'Kem iri',
            'Ketum bar',
            'Lencana terigu',
            'Lada',
            'Minyak goreng curah',
            'Segitiga terigu',
            'Sagu gunung',
            'Telor',
            'Gula Pasir',
            'Gula Merah',
            'ABC KECAP BOTOL 135ML',
            'ABC KECAP SACH',
            'ABC SAMBAL SAOS MEJA',
            'ABC SAOS SACH',
            'ABC Saos tom at m eja',
            'ABC Terasi sach',
            'ABC SARDEN 155 Gr',
            'AROMA PASTA 30ML',
            'BANGO KECAP MEJA',
            'Bango kecap reff 600',
            'Bango kecap reff 85',
            'BANGO 225 ML',
            'BANGO 1000',
            'Blueband sach 17  Gr',
            'Blueband sach 200 Gr',
            'Bola Dunia  agar',
            'BUMBU RACI K AYAM GORENG',
            'Bumbu Racik bumbu tem pe',
            'BUMBU RACI K LODEH',
            'Bumbu Racik nasi goreng',
            'BUMBU RACI K SAYUR ASEM',
            'BUMBU RACI K SOP',
            'Cangkir sarim anis',
            'Claris Tepung gula',
            'Dixi cuka 500',
            'DI XI CUKA 1000',
            'Fortune m goreng 2ltr',
            'Fortune m goreng 1ltr',
            'Hunkwee tepung',
            'Kara',
            'Kecap Botol KRAT',
            'LADAKU',
            'MASAKO AYAM',
            'Masako sapi',
            'Maya sarden 155 Gr',
            'Maya sarden 425 Gr',
            'NUTRI JELL RASA BUAH',
            'Nutrijell coklat',
            'Perm ipan',
            'PEWARNA KUPU KUPU 30 ML',
            'ROSEBRAND TEPUNG BERAS',
            'Resto m goreng  225 m l',
            'Resto 450 ML',
            'RESTO 900 ML',
            'Refina garam 250',
            'Rom an coklat bubuk',
            'Royco ayam',
            'ROYCO sapi',
            'SAJI KU TEPUNG BUMBU',
            'SAFARI MESES',
            'SAOS BOTOL KRAT',
            'Sasa 250 gr',
            'Sasa 1000',
            'Sasa 500',
            'Segitiga garam   kecil',
            'SEGI TI GA GARAM BESAR',
            'Sim as sach 200 Gr',
            'Soun Naga',
            'SP kupu kupu',
            'Stick es krim',
            'SOUN 88',
            'Swallow agar',
            'SAMHOK TERASI MEDAN',
            'Saori saos t iram',
            'Sasa 100 gr',
            'TBM',
            'Tim bangan Tepung gula',
            'Vanili R',
            'DAYAK 15',
            'Dayak 24',
            'Maskot besar',
            'Sendok kecil',
            'SENDOK kecil WARNA',
            'Sendok 24',
            'SPARTA 15',
            'Kereta 15',
            'Kereta 24',
            'Loco HDPE 15x30',
            'Loco HDPE 24x40',
            'PEONY 15',
            'PEONY 24',
            'MASCOT 10 L',
            'Attack sach 500',
            'Attack sach 1000',
            'Boom det 750  gr',
            'Bayclin botol 100m l',
            'Citrun',
            'Citra sabun',
            'Ciptadent 75 gr',
            'Carrera Shampom otor',
            'Citra bengkoang sach',
            'Clear shampoo   sach',
            'Citra bengkoang 60m l',
            'Daia 1000',
            'DOWNY SACH',
            'Dettol sabun',
            'DEE DEE PASTA GI GI 50 GR',
            'DEE DEE SHAMPO GRAPE 45 ML',
            'Dove sha sach',
            'DAI A   900GR',
            'Ekonom i EK 200',
            'EKONOMI EK 350',
            'Ekonom i EK500',
            'Em eron  h/ body 100m l',
            'Em eron sha 100m l',
            'Form ula Sikat Gigi',
            'Fresh sabun',
            'GI V sabun',
            'Head shouldr sham po sach',
            'I KAN KOI BLAU SACH',
            'KODOMO SHA 45ML',
            'KODOMO SI KAT ANAK',
            'Kispray sach',
            'Lifebouy sabun',
            'Lifebouy shampo 90 m l',
            'Lifebouy shampo sach',
            'LUX sabun',
            'Molto ultra sach',
            'MOLTO 1X BI LAS',
            'Mama lim e 80m l',
            'MAMA LI ME 160ML',
            'MBK talc baru',
            'MBK TALC SUSU',
            'Nuvo sabun',
            'PEPSODENT 190 gr',
            'Pepsodent 75gr',
            'POLYTEX SABUT SPONS',
            'Pepsodent 120 gr',
            'PONDS WHI TE FACI AL 50GR',
            'PONDS cream 20gr',
            'Pantene sha sach',
            'PROCLI N sach',
            'RI NSO CAI R',
            'RI NSO 500',
            'Rinso 1000',
            'Rapika sach',
            'Rejoice sach',
            'Rexona m an  sach',
            'Rexona women sach',
            'Soklin lantai sach',
            'SOKLI N PEWANGI SACH',
            'Sunsilk sach',
            'SOKLI N LANTAI SACH',
            'SABUT KAWAT TK- 15',
            'Shinzui sabun',
            'SUNLI GHT 200m l',
            'SUNLI GHT 90m l',
            'WPC EXTRA KUAT 400ML',
            'Zinc Shampo sach',
            'BI SKUAT BOLU',
            'BENG BENG 20GR',
            'BETTER ROMA',
            'BI G BABOL 3PCS',
            'BI SKUAT COKLAT 20GR',
            'BI SKUAT ENERGI 22. 5GR',
            'BI SKUAT SUSU 21GR',
            'BALLET TWI ST',
            'CHO CHO',
            'CHOQI CHOQI',
            'CHI KI BALLS',
            'CHEWEEZ',
            'CANNON BALL',
            'CHOKIPERO STICK',
            'CHACHA',
            'DUA KELI NCI KACANG 250 gr',
            'ESPRESSO KOPI SUSU',
            'ESCADO',
            'FULLO',
            'FRENCH FRI ES',
            'GERY COLEK',
            'GERY PASTA CHOCOLATE',
            'GERY CHOCOLATOS',
            'GERY DONUTS',
            'HELLO PANDA',
            'JETZ',
            'KERI PI K SMS',
            'KOPI KO',
            'KACANG GARI NG 500',
            'KWACI BUNGA MATAHARI',
            'KEJUCAKE',
            'LACOCO',
            'MAKARONI',
            'MENTHOS',
            'MARLEY MILK MEISES',
            'MOMOGI',
            'MI LKI TA LOLLIPOP',
            'MALKIST CRACKERS',
            'MI E GEMEZ',
            'MALKIST 500',
            'NI SSI N CRI SPY',
            'NI SSI N WAFER',
            'NABATI KEJU',
            'OI SHI SNACK',
            'OREO',
            'OPALFRUT',
            'PADI MAS BOLU',
            'PERMEN UNICAN',
            'PI LUS GARUDA 19 GR',
            'PERMEN KACA MATA',
            'PI ATTOS',
            'QTELA 23 gr',
            'BI SKUI T KELAPA ROMA',
            'RELAXA',
            'ROMA KELAPA',
            'SOSIS SONI CE',
            'SUPERMAN WAFER',
            'SARI PATI JELLY',
            'SUPERCO 24 GR',
            'SALTCHEESE COMBO',
            'SUKRO 18 GR',
            'TOP 11 GR',
            'TARO BARBEQUE',
            'TANGO 500',
            'TOGO SI IP 17. 5GR',
            'WAFFLE TANGO',
            'WAFELATOS',
            'YULI E JELLY',
            'YUPI 1000',
            'YUPI 500',
            'I ndom ie ayam bawang',
            'I ndom ie soto',
            'I ndom ie kari ayam',
            'I ndom ie goreng',
            'SEDAP KUAH',
            'Sedap goreng',
            'MI E TELOR 3 AYAM',
            'Arinda',
            'Aqua gelas',
            'Aqua Mini',
            'AQUA Galon',
            'Ale- ale',
            'AQUA 1500ML',
            'ABC Squash Delight 600 m l',
            'AQUA 600 m l',
            'JAHE MERAH AMANAH',
            'BI G COLA',
            'Coca cola sedang',
            'Extrajoss',
            'Energen',
            'ES DEGAN',
            'Fruittea box',
            'FN soda',
            'Fanta sedam g',
            'Fentania',
            'Granita',
            'GRESH',
            'Glace 600m l',
            'Happy esteler',
            'Hemaviton j reng',
            'KI KO',
            'Kratingdaeng',
            'KUKU BIMA ENERGI SACH',
            'MADU RASA',
            'MARJAN SYRUP',
            'Mizone',
            'Monair gelas',
            'NESTLE 330 ML',
            'Nice lho',
            'NUTRI SARI SACH',
            'Okky jelly drink',
            'OASIS 600 ML',
            'OASIS GLASS 240 ML',
            'PANTHER CUP',
            'PUCUK HARUM',
            'Pocari sweat botol 350 m l',
            'Pocari sweat kaleng 330m l',
            'POCARI SWEAT SACH',
            'POP ICE',
            'SANQUA 600 ML',
            'SANQUA GELAS I DUS',
            'S- Tee botol',
            'Sprite sedang',
            'SARI KACANG HI JAU 250 m l',
            'SARI KACANG I JO 200 m l',
            'Sariasem asli',
            'Tehbotol',
            'THE GELAS',
            'the gunung',
            'TRI COCO SARI KELAPA',
            'Tehkotak',
            'Tehbotol kotak 200 m l',
            'Vitcool',
            'VI T GELAS',
            'VI T 1500 ML',
            'VI T 600 ML',
            'WONG CI LI K',
            'WONGNDESO ES TELER',
            'WOW COCO',
            'ADEM SARI',
            'ALANGSARI',
            'ANAKONI DI N',
            'ANTANGI N JRG SI RUP',
            'ANTANGI N JRG TABLET',
            'ANTI MO ANAK SI ROP',
            'ANTI MO TABLET',
            'AMANPLAST',
            'ANAK SUMANG',
            'BABYS COUGH SYRUP',
            'BETADI NE 5 ML',
            'BODREX EXTRA',
            'BODREX FLU BATUK',
            'BODREX MI GRA',
            'BODREK TABLET',
            'BODREXI N',
            'COOLANT',
            'DECOLGEN',
            'DI APET',
            'FATI GON',
            'Entrostop',
            'Entrostop Anak',
            'Neozep',
            'FATI GON SPI RI T',
            'GARGLI N',
            'GELI GA BALSEM 20 GR',
            'GPU 30 ML',
            'HEROCYN',
            'HUFAGRIP PI LEK',
            'HUFAGRIP BP',
            'I NZANA',
            'I NSTO',
            'KAKI TI GA BOTOL kino',
            'KAKI TI GA KALENG',
            'KALPANAK',
            'KAPAK M ANGI N',
            'KOMI X',
            'KOMI X KI DS',
            'KONI DI N',
            'KOYO CABE',
            'KUPU KUPU PUYER',
            'LANG KP NO. 1',
            'LANG KP NO. 2',
            'LANG KP NO. 3',
            'LOTTE OBAT MATA',
            'LASERI N MADU',
            'LASERI N 30ML',
            'LANG BALSEM 10 GR',
            'LANG BALSEM 20 GR',
            'LANG MKP 4',
            'MI XAGRIP 1STRIP',
            'MEXTRI L',
            'NAPACI N NEO',
            'OBH COMBI ANAK',
            'OBH COMBI B/ F',
            'OSKADON',
            'OSKADON SP',
            'PI L KI TA',
            'PANADOL BI RU',
            'PANADOL MERAH',
            'Panadol Hijau',
            'PARAMEK',
            'PUYER BI NTANG 7',
            'PROCOLD',
            'PROMAGH',
            'REMACYL',
            'SALONPAS',
            'SANAFLU',
            'SANGOBI ON',
            'SEGAR DINGIN KECIL',
            'SEGAR DINGIN SEDANG',
            'SALEP 88',
            'SALICYL I KA',
            'SALICYL KI MI A FARMA',
            'TOLAK ANGI N CAI R',
            'TOLAK ANGI N ANAK',
            'TEH ANGI N BADAK',
            'ULTRAFLU',
            'ULTRASILI NE NEO',
            'VEGETA',
            'VEGETA HERBAL',
            'VI CK 44 ANAK 27 ML',
            'VI CK 44 27 ML',
            'VI CK VAPORUP',
            'WAI SAN',
            'ABC kopi susu',
            'ABC m occa',
            'GOODAY 3 I N1',
            'GOOD DAY FRESH',
            'I ndocafe coffeem ix',
            'Kapal api sp m ix',
            'Kapal api special 35 gr',
            'Kapal api special 65 GR',
            'KAPAL API SPECI AL 185 GR',
            'TOP KOPI SUSU',
            'TOP KOPI GULA',
            'Torabika Oke',
            'WHI TE KOFFI E',
            'Bendera kaleng coklat',
            'BENDERA KALENG PUTI H',
            'Bendera sach coklat',
            'Bendera sach putih',
            'BENDERA 195 ML',
            'Dancow sach putih',
            'DANCOW SACH CO',
            'DI AMOND CHO 200ML',
            'Diam ond kotak 125 coklat',
            'Diam ond sereal',
            'I NDOMILK 195 ML',
            'Milkuat bantal 70 m l',
            'MI LKUAT BOTOL',
            'Susu sehat ultra',
            'Ultra CO/ STW kotak 125 m l',
            'Ultra coklat kotak 200 m l',
            'Yes botol',
            'Teh Bendera bubuk',
            'Teh bendera celup 25 k',
            'Teh Bendera celup sach 5 k',
            'Teh cap botol 40 gr',
            'TEH CAP POCI merah',
            'Sariwangi celup sach 5k',
            'Sariwangi teh  asli 25k',
            'AUTAN SACH',
            'Autan junior sach',
            'Aica aibon',
            'ABC battery AA',
            'ABC battery D',
            'AMP KARET',
            'Baygon bakar 5pc',
            'Baygon cair 400 m l',
            'Baygon cair reffil 175 m l',
            'BENANG JAHI T 555',
            'BOLA PLASTI K',
            'CUP 12 OZ',
            'CHARM 1pad',
            'COTTON BODS B',
            'CELENGAN PLASTI K',
            'CHARM WI NGS 5',
            'Domestos nom os protector 5pc',
            'DOP 5watt',
            'DOP 15watt',
            'Dop 25watt',
            'DOP 10watt',
            'Etona staples no. 10',
            'KERTAS NASI GAJAH',
            'Gillette goal klik',
            'Gillette goal I I',
            'Gillette goal',
            'GOLDTAPE BENI NG',
            'GOLDTAPE HI TAM',
            'HI T cair reffil 175',
            'HI T mat 4pc',
            'HI T MAGI C',
            'HI T semprotan',
            'KI NGKONG BAKAR',
            'KOREK KAYU',
            'Laurier super maxi long',
            'Laurier super reg8pads',
            'LAKBAN',
            'LAMPU JARI MURAH',
            'KAPAS LEONY',
            'LAVENDA SACH',
            'NI CE TISSUE ROLL',
            'Power glue m urah',
            'PHILI PS 15 watt',
            'PHILI PS 25 watt',
            'PAKU PAYUNG',
            'PASEO TI SSUE',
            'LI LI N CAP PAUS',
            'Royal TI SSUE',
            'SOFELL JERUK SACH',
            'Sedotan warna',
            'STAR TI SSUE KOTAK',
            'Tokai korek gas',
            'TESSA TISUE 15',
            'TESSY TI SSU MAKAN',
            'TALI RAFIA',
            'TAMBANG 3 MM',
            'TAMBANG 4 MM',
            'TAMBANG 5 MM',
            'Tiger blades',
            'TUSUK GI GI',
            'CUSSONS BABY SABUN',
            'CERELAC BERAS M',
            'CUSSONS Bedak',
            'HAPPY BEDAK',
            'TELON LANG 25ML',
            'TELON LANG 60ML',
            'MAMYPOKO S',
            'MAMYPOKO M',
            'MAMYPOKO XL',
            'MAMYPOKO L',
            'PROMI NA SACH',
            'SWEETY L',
            'SWEETYM',
            'SWEETY S',
            'SWEETY XL',
            'Beras Murah',
            'Beras Sedang',
            'Beras Terrm ahal',
            'Beras Pera/ I R 42',
            'SUN SWALLOW SERI',
            'SUN SWALLOW TANGGUNG',
            'SWALL0W SIZE 10- 10, 5',
            'SWALLOW SERI',
            'SWALLOW SI ZE 11',
        ];

        $kategori = [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            3,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            9,
            9,
            9,
            9,
            9,
            9,
            9,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            10,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            7,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            13,
            2,
            2,
            2,
            2,
            11,
            11,
            11,
            11,
            11,
        ];

        for ($i = 1; $i <= 532; $i++) {
            $randomProduct = rand(0, 9);

            Product::create([
                'name' => $product[$i-1],
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tortor diam, ornare a diam eget, bibendum facilisis libero. Nunc porta at nisi sed interdum. Aenean semper, ipsum sed placerat dapibus, dolor enim ultrices velit, non placerat turpis sem eget velit. Suspendisse eget congue quam, nec ornare metus. Cras blandit, orci vel cursus iaculis, metus augue luctus ante, eu laoreet magna dolor in magna. Suspendisse quis ligula est. Cras malesuada leo eu hendrerit congue. Mauris non lacus eu est luctus aliquam ac sit amet nibh. Sed non ipsum tellus. Fusce pretium consequat massa id pretium. Quisque consectetur massa sed elit elementum, non cursus nisl ullamcorper. Donec finibus arcu nec quam maximus tincidunt.',
                'unit' => $unit[$randomProduct],
                'volume' => $volume[$randomProduct],
                'price' => rand(10000, 1000000),
                'picture' => 'storage/product/' . $imageProduct[rand(0, 19)],
                'stock_quantity' => 0,
                'category_id' => $kategori[$i-1],
                'suplier_id' => rand(1, 9),
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ]);
        }

        for ($i = 1; $i <= 10; $i++) {
            City::create([
                'name' => 'City ' . $i,
                'expedition_cost' => rand(1, 8) / 10,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ])->getAttributes();
        }

        for ($i = 1; $i <= 10; $i++) {
            Address::create([
                'address' => 'Address ' . $i,
                'customer_id' => $customer['id'],
                'city_id' => $i,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ])->getAttributes();
        }

        for ($i = 1; $i <= 10; $i++) {
            ExpeditionTruck::create([
                'license_id' => 'Expedition Truck ' . $i,
                'min_volume' => 18000000,
                'max_volume' => 24000000,
                'picture' => 'no-image.jpg',
                'status' => 'available',
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ])->getAttributes();
        }

        for ($i = 1; $i <= 10; $i++) {
            BankPayment::create([
                'bank_name' => 'Bank Payment ' . $i,
                'account_name' => 'Account Name BankPayment ' . $i,
                'account_number' => rand(10000000, 999999999999),
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ])->getAttributes();
        }

        //product history
        $begin = new DateTime('2017-01-01');
        $end = new DateTime('2023-01-01');

        $interval = DateInterval::createFromDateString('1 day');
        $period = new DatePeriod($begin, $interval, $end);

        foreach ($period as $dt) {
            $product_id = rand(1, 532);
            $amount_of_product = rand(500, 1000);
            $product_price = (1000 * $product_id);
            $total_price = $amount_of_product * $product_price;

            ProductHistory::create([
                'history_category' => 'in',
                'history_date' => $dt,
                'amount_of_product' => $amount_of_product,
                'product_price' => $product_price,
                'total_price' => $total_price,
                'product_expired_date' => Carbon::parse($dt)->addYears(12)->format('Y-m-d'),
                'product_id' => $product_id,
                'created_by' => $employee['id'],
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ]);

            $amount_of_product = rand(10, 20);
            $product_price = (1500 * $product_id);
            $total_price = $amount_of_product * $product_price;

            ProductHistory::create([
                'history_category' => 'out',
                'history_date' => $dt,
                'amount_of_product' => $amount_of_product,
                'product_price' => $product_price,
                'total_price' => $total_price,
                'product_expired_date' => Carbon::parse($dt)->format('Y-m-d'),
                'product_id' => $product_id,
                'created_by' => $employee['id'],
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                'deleted_at' => null,
            ]);
        }

        // transaction
        foreach ($period as $dt) {
            $loop_collection = rand(5, 10);
            $collection = new Collection;
            $subtotal = 0;
            $total_volume = 0;

            for ($i = 1; $i <= $loop_collection; $i++) {
                $amount_of_product = rand(10, 20);
                $product_id = rand(1, 532);
                $product = Product::find($product_id);
                $subtotal = $subtotal + ($product->price * $amount_of_product);
                $total_volume = $total_volume + ($product->volume * $amount_of_product);

                $collection->push((object)[
                    'amount_of_product' => $amount_of_product,
                    'product_price' => $product->price,
                    'total_price' => $product->price * $amount_of_product,
                    'status' => 'success',
                    'product_id' => $product_id,
                ]);
            }

            $address = Address::leftJoin('cities', 'addresses.city_id', '=', 'cities.id')
                ->where('addresses.customer_id', '=', $customer['id'])
                ->get();
            $address_id = rand(0, 9);
            $transaction_status_id = rand(1, 6);

            $transaction = Transaction::create([
                'subtotal_price' => $subtotal,
                'tax' => $subtotal * 0.11,
                'shipping_cost' => $address[$address_id]->expedition_cost * $total_volume,
                'grand_total_price' => $subtotal + ($subtotal * 0.11) + ($address[$address_id]->expedition_cost * $total_volume),
                'message' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tortor diam, ornare a diam eget, bibendum facilisis libero. Nunc porta at nisi sed interdum. Aenean semper, ipsum sed placerat dapibus, dolor enim ultrices velit, non placerat turpis sem eget velit. Suspendisse eget congue quam, nec ornare metus. Cras blandit, orci vel cursus iaculis, metus augue luctus ante, eu laoreet magna dolor in magna. Suspendisse quis ligula est. Cras malesuada leo eu hendrerit congue. Mauris non lacus eu est luctus aliquam ac sit amet nibh. Sed non ipsum tellus. Fusce pretium consequat massa id pretium. Quisque consectetur massa sed elit elementum, non cursus nisl ullamcorper. Donec finibus arcu nec quam maximus tincidunt.',
                'total_volume_product' => $total_volume,
                'receipt_of_payment' => 'no-image.jpg',
                'customer_id' => $customer['id'],
                'address_id' => $address[$address_id]->id,
                'bank_payment_id' => rand(1, 10),
                'transaction_status_id' => $transaction_status_id,
                'created_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
            ])->getAttributes();

            //detail transaction
            foreach ($collection as $c) {
                DetailTransaction::create([
                    'amount_of_product' => $c->amount_of_product,
                    'product_price' => $c->product_price,
                    'total_price' => $c->total_price,
                    'status' => $c->status,
                    'transaction_id' => $transaction['id'],
                    'product_id' => $c->product_id,
                    'created_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                ]);
            }

            if ($transaction_status_id === 4) {
                TransactionShipping::create([
                    'transaction_id' => $transaction['id'],
                    'employee_id' => 6,
                    'expedition_truck_id' => rand(1, 10),
                    'delivery_date' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                ]);
            }

            if ($transaction_status_id === 5 || $transaction_status_id === 6) {
                TransactionShipping::create([
                    'transaction_id' => $transaction['id'],
                    'employee_id' => 6,
                    'expedition_truck_id' => rand(1, 10),
                    'delivery_date' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                    'arrived_date' => Carbon::parse($dt)->addDays(2)->format('Y-m-d H:i:s'),
                    'created_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                    'updated_at' => Carbon::parse($dt)->format('Y-m-d H:i:s'),
                ]);
            }
        }
    }
}
